# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '发布棋谱.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
import cv2
import webbrowser
import win32con
from win32clipboard import OpenClipboard, CloseClipboard, EmptyClipboard, SetClipboardData


class Ui_ReleaseNotation(object):
    def setupUi(self, ReleaseNotation):
        ReleaseNotation.setObjectName("ReleaseNotation")
        ReleaseNotation.resize(430, 261)
        ReleaseNotation.setMinimumSize(QtCore.QSize(430, 261))
        ReleaseNotation.setMaximumSize(QtCore.QSize(430, 261))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReleaseNotation.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReleaseNotation.sizePolicy().hasHeightForWidth())
        ReleaseNotation.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(ReleaseNotation)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 121))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 391, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.radioButton_origin = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_origin.setIconSize(QtCore.QSize(15, 15))
        self.radioButton_origin.setChecked(True)
        self.radioButton_origin.setObjectName("radioButton_origin")
        self.horizontalLayout_2.addWidget(self.radioButton_origin)
        self.radioButton_resize = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_resize.setIconSize(QtCore.QSize(15, 15))
        self.radioButton_resize.setObjectName("radioButton_resize")
        self.horizontalLayout_2.addWidget(self.radioButton_resize)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(112, 0))
        self.label_3.setMaximumSize(QtCore.QSize(112, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.radioButton_custom = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_custom.setMaximumSize(QtCore.QSize(100, 16777215))
        self.radioButton_custom.setIconSize(QtCore.QSize(15, 15))
        self.radioButton_custom.setObjectName("radioButton_custom")
        self.horizontalLayout_3.addWidget(self.radioButton_custom)
        self.lineEdit_width = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_width.setMinimumSize(QtCore.QSize(45, 0))
        self.lineEdit_width.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lineEdit_width.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.horizontalLayout_3.addWidget(self.lineEdit_width)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_height = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_height.setMinimumSize(QtCore.QSize(45, 0))
        self.lineEdit_height.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lineEdit_height.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.horizontalLayout_3.addWidget(self.lineEdit_height)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_path = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_path.setObjectName("lineEdit_path")
        self.horizontalLayout.addWidget(self.lineEdit_path)
        self.pushButton_search = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_search.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_search.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.pushButton_saveAs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_saveAs.setEnabled(False)
        self.pushButton_saveAs.setObjectName("pushButton_saveAs")
        self.horizontalLayout.addWidget(self.pushButton_saveAs)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(ReleaseNotation)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 411, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 391, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.radioButton_notation = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_notation.setIconSize(QtCore.QSize(15, 15))
        self.radioButton_notation.setObjectName("radioButton_notation")
        self.horizontalLayout_6.addWidget(self.radioButton_notation)
        self.radioButton_image = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_image.setIconSize(QtCore.QSize(15, 15))
        self.radioButton_image.setObjectName("radioButton_image")
        self.horizontalLayout_6.addWidget(self.radioButton_image)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 25))
        self.comboBox.setMaximumSize(QtCore.QSize(150, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(ReleaseNotation)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 220, 411, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_release = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_release.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_release.setObjectName("pushButton_release")
        self.horizontalLayout_8.addWidget(self.pushButton_release)
        self.pushButton_close = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_close.setMaximumSize(QtCore.QSize(90, 30))
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout_8.addWidget(self.pushButton_close)

        self.retranslateUi(ReleaseNotation)
        QtCore.QMetaObject.connectSlotsByName(ReleaseNotation)

    def retranslateUi(self, ReleaseNotation):
        _translate = QtCore.QCoreApplication.translate
        ReleaseNotation.setWindowTitle(_translate("ReleaseNotation", "发布棋谱"))
        self.groupBox.setTitle(_translate("ReleaseNotation", "棋盘"))
        self.label.setText(_translate("ReleaseNotation", "图片大小"))
        self.radioButton_origin.setText(_translate("ReleaseNotation", "原图"))
        self.radioButton_resize.setText(_translate("ReleaseNotation", "调整后大小"))
        self.radioButton_custom.setText(_translate("ReleaseNotation", "自定义大小"))
        self.label_2.setText(_translate("ReleaseNotation", "×"))
        self.pushButton_search.setText(_translate("ReleaseNotation", "浏览"))
        self.pushButton_saveAs.setText(_translate("ReleaseNotation", "图片另存为"))
        self.groupBox_2.setTitle(_translate("ReleaseNotation", "发布"))
        self.label_6.setText(_translate("ReleaseNotation", "发布内容"))
        self.radioButton_notation.setText(_translate("ReleaseNotation", "棋谱"))
        self.radioButton_image.setText(_translate("ReleaseNotation", "当前局面"))
        self.label_7.setText(_translate("ReleaseNotation", "发布站点"))
        self.comboBox.setItemText(0, _translate("ReleaseNotation", "百度知道"))
        self.comboBox.setItemText(1, _translate("ReleaseNotation", "百度贴吧象棋吧"))
        self.comboBox.setItemText(2, _translate("ReleaseNotation", "知乎"))
        self.comboBox.setItemText(3, _translate("ReleaseNotation", "新浪微博"))
        self.comboBox.setItemText(4, _translate("ReleaseNotation", "QQ空间"))
        self.comboBox.setItemText(5, _translate("ReleaseNotation", "其他"))
        self.pushButton_release.setText(_translate("ReleaseNotation", "发布"))
        self.pushButton_close.setText(_translate("ReleaseNotation", "关闭"))


class win_ReleaseNotation(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(win_ReleaseNotation, self).__init__(parent)
        self.ui = Ui_ReleaseNotation()
        self.ui.setupUi(self)
        self.init_slots()

    def init_slots(self):
        self.ui.pushButton_search.clicked.connect(self.search)
        self.ui.pushButton_saveAs.clicked.connect(self.saveAs)
        self.ui.pushButton_release.clicked.connect(self.release)
        self.ui.pushButton_close.clicked.connect(self.Close)

    def img_resize(self, image, width=0, height=0):
        if width == height == 0:
            width, height = len(image[0]), len(image)
            if height >= width:
                width = int(width / (height / self.std))
                height = self.std
            else:
                height = int(height / (width / self.std))
                width = self.std
        return cv2.resize(image, dsize=(width, height), interpolation=cv2.INTER_AREA)

    def search(self):
        fileName, filetype = QFileDialog.getSaveFileName(self, "请选择保存路径", "", "*.jpg;;*.png;;All Files(*)")
        if fileName != "":
            self.ui.lineEdit_path.setText(fileName)
            self.ui.pushButton_saveAs.setEnabled(True)

    def saveAs(self):
        fileName = self.ui.lineEdit_path.text()
        if fileName != "":
            if self.ui.radioButton_resize.isChecked():
                outputImg = self.img_resize(self.image)
            elif self.ui.radioButton_custom.isChecked():
                height, width = self.ui.lineEdit_height.text(), self.ui.lineEdit_width.text()
                if height.isdigit() and width.isdigit():
                    if 0 < int(height) <= 10000 and 0 < int(width) <= 10000:
                        outputImg = self.img_resize(self.image, int(width), int(height))
                    else:
                        QtWidgets.QMessageBox.warning(self, u"中国象棋自动打谱工具", u"图片的尺寸范围为0~10000")
                        return
                else:
                    QtWidgets.QMessageBox.warning(self, u"中国象棋自动打谱工具", u"请输入数字！")
                    return
            else:
                outputImg = self.image
            try:
                cv2.imwrite(fileName, outputImg)
            except:
                QtWidgets.QMessageBox.warning(self, u"中国象棋自动打谱工具", u"保存失败，请检查路径是否正确！")
        else:
            QtWidgets.QMessageBox.warning(self, u"中国象棋自动打谱工具", u"请输入文件路径！")

    def release(self):
        if self.ui.comboBox.currentText() == "百度知道":
            webbrowser.open("https://zhidao.baidu.com/")
        elif self.ui.comboBox.currentText() == "百度贴吧象棋吧":
            webbrowser.open("https://tieba.baidu.com/f?ie=utf-8&kw=%E8%B1%A1%E6%A3%8B")
        elif self.ui.comboBox.currentText() == "知乎":
            webbrowser.open("https://www.zhihu.com/")
        elif self.ui.comboBox.currentText() == "新浪微博":
            webbrowser.open("https://www.weibo.com/")
        elif self.ui.comboBox.currentText() == "QQ空间":
            webbrowser.open("https://i.qq.com/")
        OpenClipboard()
        EmptyClipboard()
        clipboard = self.notation if self.ui.radioButton_notation.isChecked() else self.board
        data = "棋谱" if self.ui.radioButton_notation.isChecked() else "当前局面"
        SetClipboardData(win32con.CF_UNICODETEXT, clipboard)
        CloseClipboard()
        QtWidgets.QMessageBox.information(self, u"中国象棋自动打谱工具", u"%s已复制到剪贴板，请找到发表帖子的内容框并进行粘贴。" % data)

    def Close(self):
        self.close()

    def get_data(self, ls):
        self.notation, self.board = ls[0], ls[1]

    def get_data_image(self, image):
        self.image = image

    def get_data_resize(self, std):
        self.std = std
